name: aipl-testing
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  run-tests:

    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install pytest
        export PYTHONPATH=.

    - name: Ensure it starts up
      run: bin/aipl -h

    - name: Run tests
      run: pytest .
